"""
Django settings for telegram_bot project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t3q5hjtwozc&^*-^u0gn&^#@44r3m9dy%5b(j^1v3+oq6o=siz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "*",
    "https://statute-competitive-doll-compatible.trycloudflare.com",
    "https://candidate-translate-pill-roles.trycloudflare.com",
    "https://el-veco-bot.onrender.com",
]

CHAT_WEBHOOK = 'https://conexionai.app.n8n.cloud/webhook/2305f427-849e-4111-a040-25e5de928328/chat'
# Application definition
BOT_TOKEN = "7636265328:AAEm61HH_bCM-5zuBIZWbxkZL62T7uBaNnM"

# Configuraciones adicionales para settings.py

# Webhook del chat embedded
CHAT_WEBHOOK_URL = "https://conexionai.app.n8n.cloud/webhook/2305f427-849e-4111-a040-25e5de928328/chat"

# Configuración del chat
CHAT_TIMEOUT = 30  # segundos
CHAT_MAX_RETRIES = 3

# URLs para el webhook del chat (si usas el método web)

# Configuración de requests
REQUESTS_TIMEOUT = 30
REQUESTS_RETRIES = 3
OPENAI_KEY = "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"

INSTALLED_APPS = [
    'bot',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
GOOGLE_CREDS_PATH = os.path.join(BASE_DIR, "credentials/credentials.json")
GOOGLE_FOLDER_ID = '1lB2gDxcysBi13WnV4-2_g1FKZx0jskdE'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'telegram_bot.urls'



WSGI_APPLICATION = 'telegram_bot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Set default values for the environment variables if they’re not already set


DATABASES = {

}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
